### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by wosergame** [Niam5/Eluna-CMaNGOS-TBC#12]
Hello. I use a bunch of ai bots, playerbots, solocraft on win. 
If you disable AiPlayerbot.AutoDoQuests = 0 in aiplayerbot.conf, then the crash does not repeat.
P.S : When compiling, I disable BUILD_ELUNA in cmake. There are many errors related to BG and arenas (after leaving the battlefield, the server crashes).

Very often there is a crash :

[Git repo_mangosd.exe_[12-5_20-2-28].txt](https://github.com/Eluna-Ports/Eluna-CMaNGOS-TBC/files/15287368/Git.repo_mangosd.exe_.12-5_20-2-28.txt)

Thanks for your attention.

**Comment by Niam5** [comment]
The provided file seems to indicate an issue with a mysql component

Fault address:  000007FEE6994AD2 01:0000000000063AD2 C:\burning\libmysql.dll

Also I'm not going to put much time into figuring this out in your current configuration since you are using Windows 7 and anything under Windows 10 is at your own risk. Even the CMaNGOS main website says Windows 10+ supported.

**Comment by wosergame** [comment]
> The provided file seems to indicate an issue with a mysql component
> 
> Fault address: 000007FEE6994AD2 01:0000000000063AD2 C:\burning\libmysql.dll
> 
> Also I'm not going to put much time into figuring this out in your current configuration since you are using Windows 7 and anything under Windows 10 is at your own risk. Even the CMaNGOS main website says Windows 10+ supported.

Switched to win 10. Crash remained.
Maybe you need to install some software besides the ready-made kernel?
I've tried it MySQL 8.0.31 / 8.0.37
Additionally I tried libmysql.dll from https://github.com/Eluna-Ports/Eluna-CMaNGOS-TBC/releases.

[Git repo_mangosd.exe_[14-5_18-8-50].txt](https://github.com/Eluna-Ports/Eluna-CMaNGOS-TBC/files/15310833/Git.repo_mangosd.exe_.14-5_18-8-50.txt)

**Comment by Niam5** [comment]
I also need all scripts you are running.

**Comment by wosergame** [comment]
> I also need all scripts you are running.
>

Ok, where do I find out?

![изображение_2024-05-14_215406276](https://github.com/Eluna-Ports/Eluna-CMaNGOS-TBC/assets/78369752/4f0f81b2-1336-49b0-957f-3e10348b012d)

[aiplayerbot.txt](https://github.com/Eluna-Ports/Eluna-CMaNGOS-TBC/files/15312200/aiplayerbot.txt)
[mangosd.txt](https://github.com/Eluna-Ports/Eluna-CMaNGOS-TBC/files/15312216/mangosd.txt)

**Comment by Niam5** [comment]
What lua files have you placed in the lua_scripts directory.

**Comment by wosergame** [comment]
> What lua files have you placed in the lua_scripts directory.

None.
Eluna.Enabled = 0

If you turn on eluna, crashes appear when leaving the battlefield and arena. (https://github.com/Eluna-Ports/Eluna-CMaNGOS-TBC/issues/8)

**Comment by Niam5** [comment]
Looking at you cmake, with the Eluna checkbox unchecked Eluna doesn't build. Also using the DEPRICATED_PLAYERBOT options gets disabled under the hood since that and the ike3 bots can't coexist. I would say to uncheck Solocraft and leave Eluna unchecked in cmake and see if the crashes still occur to limit the amount of different things going on since you have so many enabled.

**Comment by Niam5** [comment]
Also send me your playerbotai.conf file please so I can have the same settings

**Comment by Niam5** [comment]
Actually may not need any files from you. The upstream branch has the same bug so Ill report it there.

**Comment by wosergame** [comment]
> Looking at you cmake, with the Eluna checkbox unchecked Eluna doesn't build. Also using the DEPRICATED_PLAYERBOT options gets disabled under the hood since that and the ike3 bots can't coexist. I would say to uncheck Solocraft and leave Eluna unchecked in cmake and see if the crashes still occur to limit the amount of different things going on since you have so many enabled.

but I use this core for the sake of ike3 bots and solocraft :(

**Comment by Niam5** [comment]
It was to test if any of them were the cause of the crash, to remove as
many variables as possible. However, it doesn't matter since o was able to
reproduce the crash or at least one similar to it and also determined that
the same crash exists in the upstream project so it's not the modifications
causing the issue. I have already reported the issue and sent the data to
the playerbot dev for him to investigate.

**Comment by wosergame** [comment]
> It was to test if any of them were the cause of the crash, to remove as many variables as possible. However, it doesn't matter since o was able to reproduce the crash or at least one similar to it and also determined that the same crash exists in the upstream project so it's not the modifications causing the issue. I have already reported the issue and sent the data to the playerbot dev for him to investigate.

Thank you, we will be waiting

**Comment by wosergame** [comment]
> It was to test if any of them were the cause of the crash, to remove as many variables as possible. However, it doesn't matter since o was able to reproduce the crash or at least one similar to it and also determined that the same crash exists in the upstream project so it's not the modifications causing the issue. I have already reported the issue and sent the data to the playerbot dev for him to investigate.

https://github.com/cmangos/playerbots/commit/2ad028a507c1cd36f66345dd61df6bb390c1a822 
this solves the problem

**Comment by Niam5** [comment]
Playerbots repo fork updated.
